name: Xcode

on: push

jobs:
  unit_tests:
    name: Unit tests
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        uses: docker://swift:5.1.2
        with:
          entrypoint: swift
          args: build
